name: candle
channels:
  - conda-forge
  - nodefaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.43.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.2
  - pip=23.2.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.1.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.2.6
  - pip:
      - appnope==0.1.3
      - astropy==5.3.3
      - asttokens==2.4.0
      - backcall==0.2.0
      - candle==0.0.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - decorator==5.1.1
      - executing==1.2.0
      - filelock==3.12.3
      - fonttools==4.42.1
      - idna==3.4
      - ipython==8.15.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.25.2
      - packaging==23.1
      - pandas==2.1.0
      - parso==0.8.3
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - prompt-toolkit==3.0.39
      - protobuf==3.20.0
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyerfa==2.0.0.3
      - pyg-lib==0.2.0+pt20
      - pygments==2.16.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - requests==2.31.0
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - six==1.16.0
      - stack-data==0.6.2
      - statsmodels==0.14.0
      - sympy==1.12
      - threadpoolctl==3.2.0
      - torch==2.0.1
      - torch-cluster==1.6.1
      - torch-geometric==2.3.1
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
      - torch-spline-conv==1.2.2
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tqdm==4.66.1
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==2.0.4
      - wcwidth==0.2.6
